/* generatorData.js — 30 countries, real postal codes, large name pools */
/* Auto-converted from data.js to ES module format */

/* ─── Helpers used by phone functions ─── */
const r  = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min
const rp = () => String(r(10, 99))


export const FLAGS={
  FR:'🇫🇷',US:'🇺🇸',UK:'🇬🇧',DE:'🇩🇪',IT:'🇮🇹',ES:'🇪🇸',JP:'🇯🇵',IN:'🇮🇳',
  BR:'🇧🇷',CA:'🇨🇦',AU:'🇦🇺',NL:'🇳🇱',PT:'🇵🇹',SE:'🇸🇪',NO:'🇳🇴',DK:'🇩🇰',
  FI:'🇫🇮',PL:'🇵🇱',CZ:'🇨🇿',AT:'🇦🇹',CH:'🇨🇭',BE:'🇧🇪',RU:'🇷🇺',CN:'🇨🇳',
  KR:'🇰🇷',MX:'🇲🇽',AR:'🇦🇷',ZA:'🇿🇦',NG:'🇳🇬',EG:'🇪🇬',TR:'🇹🇷',SA:'🇸🇦',
  PH:'🇵🇭',ID:'🇮🇩',MY:'🇲🇾',TH:'🇹🇭',VN:'🇻🇳',PK:'🇵🇰',BD:'🇧🇩',GH:'🇬🇭'
};

export const AVC=[
  ['#00f0ff','rgba(0,240,255,0.13)'],['#b47aff','rgba(180,122,255,0.13)'],
  ['#ff3cac','rgba(255,60,172,0.13)'],['#00ffa3','rgba(0,255,163,0.13)'],
  ['#ffd700','rgba(255,215,0,0.13)'],['#ff6b35','rgba(255,107,53,0.13)'],
  ['#39ff14','rgba(57,255,20,0.13)'],['#ff007f','rgba(255,0,127,0.13)']
];

export const D={
  FR:{name:'France',
    male:['Lucas','Hugo','Tom','Léo','Noah','Théo','Louis','Enzo','Adam','Raphaël','Antoine','Pierre','Jules','Paul','Baptiste','Maxime','Clément','Gabriel','Axel','Romain','Nathan','Nicolas','Quentin','Alexis','Julien','Thomas','Matthieu','Florian','Adrien','Victor','Ethan','Arthur','Charles','Edouard','Timothée'],
    female:['Emma','Jade','Léa','Manon','Inès','Chloé','Camille','Zoé','Sarah','Alice','Lucie','Marine','Clara','Juliette','Elisa','Oceane','Pauline','Laura','Julie','Marie','Charlotte','Amandine','Laure','Sophie','Margaux','Mathilde','Céline','Audrey','Sandrine','Nathalie','Isabelle','Christine','Virginie','Delphine','Valérie'],
    last:['Martin','Bernard','Dubois','Thomas','Robert','Richard','Petit','Durand','Leroy','Moreau','Simon','Laurent','Lefebvre','Michel','Garcia','Roux','David','Bertrand','Morel','Fournier','Girard','Bonnet','Dupont','Lambert','Fontaine','Rousseau','Vincent','Muller','Lefevre','Faure','Andre','Mercier','Blanc','Guerin','Boyer'],
    streets:['Rue de la Paix','Rue des Lilas','Avenue Victor Hugo','Boulevard Haussmann','Rue du Faubourg Saint-Antoine','Rue de Rivoli','Avenue Montaigne','Rue Oberkampf','Impasse des Roses','Allée des Peupliers','Rue Saint-Denis','Boulevard Voltaire','Rue Lafayette','Rue de Bretagne','Avenue de la République','Rue du Temple','Boulevard Beaumarchais','Rue de Turbigo'],
    apt:['Apt 2A','Apt 3B','Appartement 4C','Bâtiment B–12','Studio 1er étage','Apt 7','Rez-de-chaussée','Appt 15','Bât. A Apt 6','Apt 11B'],
    cities:[{n:'Paris',z:'75001'},{n:'Paris',z:'75008'},{n:'Paris',z:'75011'},{n:'Paris',z:'75015'},{n:'Paris',z:'75018'},{n:'Lyon',z:'69001'},{n:'Lyon',z:'69003'},{n:'Marseille',z:'13001'},{n:'Marseille',z:'13008'},{n:'Toulouse',z:'31000'},{n:'Nice',z:'06000'},{n:'Nantes',z:'44000'},{n:'Strasbourg',z:'67000'},{n:'Bordeaux',z:'33000'},{n:'Rennes',z:'35000'},{n:'Grenoble',z:'38000'},{n:'Montpellier',z:'34000'},{n:'Lille',z:'59000'}],
    phone:function(){return '+33 '+r(6,9)+' '+rp()+' '+rp()+' '+rp()+' '+rp()}},

  US:{name:'United States',
    male:['James','John','Robert','Michael','William','David','Richard','Joseph','Thomas','Charles','Daniel','Matthew','Anthony','Mark','Donald','Steven','Paul','Andrew','Kenneth','Joshua','Kevin','Brian','George','Edward','Ronald','Timothy','Jason','Jeffrey','Ryan','Jacob','Gary','Eric','Jonathan','Stephen','Larry'],
    female:['Mary','Patricia','Jennifer','Linda','Barbara','Susan','Jessica','Sarah','Karen','Lisa','Nancy','Betty','Margaret','Sandra','Ashley','Dorothy','Kimberly','Emily','Donna','Michelle','Carol','Amanda','Melissa','Deborah','Stephanie','Rebecca','Sharon','Laura','Cynthia','Kathleen','Amy','Angela','Shirley','Anna','Brenda'],
    last:['Smith','Johnson','Williams','Brown','Jones','Garcia','Miller','Davis','Martinez','Wilson','Anderson','Taylor','Thomas','Hernandez','Moore','Jackson','White','Harris','Martin','Thompson','Young','Hall','Walker','Allen','King','Wright','Scott','Torres','Nguyen','Hill','Flores','Green','Adams','Nelson','Baker'],
    streets:['Oak Street','Maple Avenue','Elm Drive','Cedar Lane','Pine Road','Willow Way','Lakeview Drive','Sunset Boulevard','River Road','Hillcrest Avenue','Main Street','Washington Blvd','Lincoln Avenue','Park Place','Broadway','Jefferson Drive','Roosevelt Way','Franklin Street','Madison Avenue','Monroe Boulevard'],
    apt:['Apt 1A','Suite 200','Unit 4B','Apt 12','Unit 3C','Suite 101','Apt 2','Floor 3 Unit 7','Unit 15','Suite 5B'],
    cities:[{n:'New York',z:'10001'},{n:'New York',z:'10019'},{n:'New York',z:'10036'},{n:'Los Angeles',z:'90001'},{n:'Los Angeles',z:'90036'},{n:'Chicago',z:'60601'},{n:'Chicago',z:'60614'},{n:'Houston',z:'77001'},{n:'Phoenix',z:'85001'},{n:'Philadelphia',z:'19103'},{n:'San Diego',z:'92101'},{n:'Dallas',z:'75201'},{n:'Austin',z:'78701'},{n:'San Francisco',z:'94102'},{n:'Seattle',z:'98101'},{n:'Boston',z:'02101'},{n:'Miami',z:'33101'},{n:'Denver',z:'80201'}],
    phone:function(){return '+1 ('+r(200,999)+') '+r(200,999)+'-'+r(1000,9999)}},

  UK:{name:'United Kingdom',
    male:['Oliver','George','Harry','Jack','Noah','Charlie','Jacob','Alfie','Oscar','Archie','Henry','Leo','Theo','William','James','Logan','Ethan','Mason','Luca','Isaac','Frederick','Tobias','Sebastian','Arthur','Edward','Alexander','Dylan','Finley','Zachary','Elliot'],
    female:['Olivia','Amelia','Isla','Ava','Mia','Isabella','Sophia','Grace','Lily','Freya','Poppy','Rosie','Emily','Ella','Evie','Hannah','Jessica','Chloe','Lucy','Daisy','Imogen','Charlotte','Scarlett','Phoebe','Ellie','Millie','Harriet','Alice','Florence','Eleanor'],
    last:['Smith','Jones','Williams','Taylor','Brown','Davies','Evans','Wilson','Thomas','Roberts','Johnson','Lewis','Walker','Robinson','Wood','Thompson','White','Watson','Jackson','Wright','Green','Hall','Harris','Clarke','Cooper','Mitchell','Hughes','Ward','Morgan','Bell'],
    streets:['High Street','Church Lane','Victoria Road','Kings Road','Queen Street','London Road','Station Road','Park Avenue','Manor Drive','The Grove','Elm Close','Oak Avenue','Brook Lane','Mill Road','Church Street','Market Place','Castle Street','Bridge Road','Water Lane','Chapel Street'],
    apt:['Flat 2','Flat 3B','Flat 10','Ground Floor','First Floor','Flat A','Studio 4','Flat 7','Flat 1C','Flat 22'],
    cities:[{n:'London',z:'EC1A 1BB'},{n:'London',z:'W1A 1AA'},{n:'London',z:'SW1A 2AA'},{n:'London',z:'WC2N 5DU'},{n:'Manchester',z:'M1 1AE'},{n:'Manchester',z:'M2 4WU'},{n:'Birmingham',z:'B1 1BB'},{n:'Leeds',z:'LS1 1BA'},{n:'Glasgow',z:'G1 1DX'},{n:'Liverpool',z:'L1 8JQ'},{n:'Bristol',z:'BS1 4DJ'},{n:'Edinburgh',z:'EH1 1YZ'},{n:'Cardiff',z:'CF10 1EP'},{n:'Sheffield',z:'S1 2HE'},{n:'Oxford',z:'OX1 2JD'},{n:'Cambridge',z:'CB2 1TN'}],
    phone:function(){return '+44 7'+r(100,999)+' '+r(100,999)+' '+r(100,999)}},

  DE:{name:'Germany',
    male:['Lukas','Jonas','Leon','Felix','Luca','Tim','Finn','Noah','Elias','Paul','Maximilian','Jan','Tobias','Nico','Philipp','Fabian','Moritz','Simon','Julian','Florian','Markus','Stefan','Christian','Michael','Thomas','Andreas','Klaus','Jürgen','Werner','Dieter','Hans','Walter','Karl','Bernd','Ralf'],
    female:['Lena','Emma','Mia','Sofia','Anna','Laura','Lea','Hannah','Lina','Marie','Sophie','Maja','Julia','Katharina','Sarah','Nina','Lisa','Alina','Amelie','Jana','Petra','Sabine','Andrea','Monika','Claudia','Susanne','Ute','Birgit','Helga','Renate','Brigitte','Ingrid','Martina','Christine','Barbara'],
    last:['Müller','Schmidt','Schneider','Fischer','Weber','Meyer','Wagner','Becker','Schulz','Hoffmann','Schäfer','Koch','Bauer','Richter','Klein','Wolf','Schröder','Neumann','Schwarz','Zimmermann','Krüger','Hartmann','Lange','Köhler','Braun','Krause','Werner','Schmitt','Lehmann','Maier'],
    streets:['Hauptstraße','Bahnhofstraße','Schillerstraße','Goethestraße','Gartenstraße','Lindenweg','Rosenstraße','Bergstraße','Waldweg','Beethovenstraße','Mozartweg','Friedrichstraße','Karlstraße','Bismarckstraße','Kirchstraße','Schulstraße','Parkstraße','Wilhelmstraße'],
    apt:['Whg. 3','Whg. 12A','EG rechts','1. OG links','Whg. 5B','Dachgeschoss','Whg. 2','Whg. 8C','2. OG','Whg. 17'],
    cities:[{n:'Berlin',z:'10115'},{n:'Berlin',z:'10178'},{n:'Berlin',z:'10243'},{n:'Hamburg',z:'20095'},{n:'Hamburg',z:'20354'},{n:'Munich',z:'80331'},{n:'Munich',z:'80539'},{n:'Cologne',z:'50667'},{n:'Frankfurt',z:'60311'},{n:'Stuttgart',z:'70173'},{n:'Düsseldorf',z:'40213'},{n:'Dortmund',z:'44135'},{n:'Leipzig',z:'04109'},{n:'Dresden',z:'01067'},{n:'Nuremberg',z:'90402'},{n:'Bremen',z:'28195'}],
    phone:function(){return '+49 '+r(170,179)+' '+r(1000000,9999999)}},

  IT:{name:'Italy',
    male:['Luca','Matteo','Leonardo','Lorenzo','Francesco','Alessandro','Marco','Davide','Andrea','Simone','Gabriele','Riccardo','Tommaso','Filippo','Edoardo','Daniele','Michele','Stefano','Giacomo','Giovanni','Roberto','Antonio','Giuseppe','Mario','Luigi','Sergio','Fabio','Claudio','Massimo','Alberto'],
    female:['Giulia','Sofia','Aurora','Alice','Martina','Emma','Sara','Chiara','Valentina','Alessia','Giorgia','Federica','Serena','Elisa','Camilla','Eleonora','Francesca','Beatrice','Roberta','Monica','Paola','Silvia','Cristina','Laura','Elena','Simona','Angela','Rosa','Anna','Maria'],
    last:['Rossi','Ferrari','Russo','Bianchi','Romano','Gallo','Costa','Fontana','Conti','Esposito','Ricci','Bruno','De Luca','Moretti','Barbieri','Lombardi','Mariotti','Galli','Cattaneo','Rinaldi','Pellegrini','Caruso','Greco','Martini','Ferraro','Mancini','Rizzo','Santoro','Vitale','Mariani'],
    streets:['Via Roma','Via Garibaldi','Corso Italia','Via Mazzini','Via Nazionale','Via Dante','Viale dei Tigli','Via Cavour','Via Verdi','Via Marconi','Corso Umberto','Via Amendola','Via Leopardi','Via Colombo','Via Rossini','Corso Vittorio Emanuele','Via Matteotti','Piazza della Repubblica'],
    apt:['Int. 3','Scala A Int. 5','Piano 2 Int. 7','Int. 1','Scala B','Piano Terra','Int. 12','Attico','Int. 4B','Scala C Int. 9'],
    cities:[{n:'Rome',z:'00100'},{n:'Rome',z:'00118'},{n:'Rome',z:'00187'},{n:'Milan',z:'20121'},{n:'Milan',z:'20135'},{n:'Naples',z:'80121'},{n:'Turin',z:'10121'},{n:'Palermo',z:'90121'},{n:'Genoa',z:'16121'},{n:'Bologna',z:'40121'},{n:'Florence',z:'50123'},{n:'Bari',z:'70121'},{n:'Catania',z:'95121'},{n:'Venice',z:'30121'},{n:'Verona',z:'37121'},{n:'Padua',z:'35121'}],
    phone:function(){return '+39 3'+r(10,99)+' '+r(1000000,9999999)}},

  ES:{name:'Spain',
    male:['Alejandro','Daniel','Pablo','Carlos','Miguel','David','Javier','Antonio','Manuel','Jorge','Sergio','Óscar','Álvaro','Adrián','Rubén','Marcos','Rodrigo','Iván','Raúl','Víctor','José','Francisco','Juan','Luis','Pedro','Jesús','Rafael','Fernando','Diego','Enrique'],
    female:['Lucía','María','Paula','Sara','Laura','Marta','Elena','Carmen','Ana','Isabel','Cristina','Nuria','Raquel','Patricia','Beatriz','Silvia','Mónica','Rosa','Pilar','Inmaculada','Sofía','Valentina','Claudia','Andrea','Natalia','Verónica','Teresa','Dolores','Amparo','Consuelo'],
    last:['García','Martínez','López','Sánchez','González','Pérez','Rodríguez','Fernández','Torres','Ramírez','Flores','Cruz','Jiménez','Álvarez','Moreno','Molina','Romero','Navarro','Ortega','Castro','Vega','Ramos','Díaz','Herrero','Muñoz','Alonso','Gutiérrez','Iglesias','Blanco','Domínguez'],
    streets:['Calle Mayor','Gran Vía','Av. de la Constitución','Calle del Prado','Paseo de Gracia','Calle Serrano','Calle Alcalá','Rambla Catalunya','Calle Colón','Calle Real','Calle Balmes','Paseo de la Castellana','Calle Fuencarral','Calle Velázquez','Av. Diagonal'],
    apt:['Piso 2B','Bajo izquierda','3º derecha','Ático','Piso 5A','Entresuelo','Local 3','Piso 1 izq.','Bajo derecha','Piso 4C'],
    cities:[{n:'Madrid',z:'28001'},{n:'Madrid',z:'28013'},{n:'Madrid',z:'28045'},{n:'Barcelona',z:'08001'},{n:'Barcelona',z:'08015'},{n:'Valencia',z:'46001'},{n:'Seville',z:'41001'},{n:'Zaragoza',z:'50001'},{n:'Málaga',z:'29001'},{n:'Bilbao',z:'48001'},{n:'Alicante',z:'03001'},{n:'Córdoba',z:'14001'},{n:'Valladolid',z:'47001'},{n:'Granada',z:'18001'},{n:'Murcia',z:'30001'}],
    phone:function(){return '+34 6'+r(10,99)+' '+r(100,999)+' '+r(100,999)}},

  JP:{name:'Japan',
    male:['Haruto','Sota','Yuki','Hayato','Haruki','Ryusei','Koki','Sora','Yuto','Ren','Kaito','Shun','Takumi','Daiki','Taisei','Riku','Hinata','Yusei','Kenta','Aoi','Kazuki','Ryo','Yuma','Sota','Itsuki','Hiroki','Takeshi','Kenji','Satoshi','Naoki'],
    female:['Yui','Hina','Sakura','Aoi','Rin','Mio','Koharu','Nanami','Hinata','Yuna','Mitsuki','Miyu','Haruka','Riko','Nana','Saki','Mei','Akari','Yuki','Rena','Hana','Ayaka','Misaki','Emi','Kaede','Nozomi','Yurina','Satsuki','Momoka','Kotone'],
    last:['Sato','Suzuki','Takahashi','Tanaka','Ito','Watanabe','Yamamoto','Nakamura','Kobayashi','Kato','Yoshida','Yamada','Sasaki','Yamaguchi','Matsumoto','Inoue','Kimura','Hayashi','Shimizu','Yamazaki','Mori','Abe','Ikeda','Hashimoto','Yamashita','Ishikawa','Nakagawa','Ogawa','Fujita','Okamoto'],
    streets:['Sakura-dori','Ginza-dori','Shinjuku-dori','Omotesando-dori','Yamate-dori','Chuo-dori','Meiji-dori','Aoyama-dori','Takeshita-dori','Nakamise-dori','Kitano-dori','Sanjo-dori','Kawaramachi-dori','Gojo-dori'],
    apt:['Room 302','#205','Unit 4F','Room 101','#503','Unit 2A','Room 12','#610','Unit 8B','Room 204'],
    cities:[{n:'Tokyo',z:'100-0001'},{n:'Tokyo',z:'100-0005'},{n:'Tokyo',z:'150-0001'},{n:'Osaka',z:'530-0001'},{n:'Osaka',z:'542-0081'},{n:'Nagoya',z:'460-0001'},{n:'Sapporo',z:'060-0001'},{n:'Fukuoka',z:'810-0001'},{n:'Kobe',z:'650-0001'},{n:'Kyoto',z:'600-8001'},{n:'Hiroshima',z:'730-0011'},{n:'Sendai',z:'980-0021'},{n:'Yokohama',z:'220-0012'}],
    phone:function(){return '+81 '+r(70,90)+'-'+r(1000,9999)+'-'+r(1000,9999)}},

  IN:{name:'India',
    male:['Aarav','Vihaan','Arjun','Sai','Reyansh','Ayaan','Vivaan','Aditya','Rohan','Arnav','Harsh','Dev','Krishna','Yash','Kabir','Ishaan','Rudra','Karan','Aman','Raj','Rahul','Amit','Suresh','Vijay','Ramesh','Mahesh','Rakesh','Rajesh','Naresh','Dinesh','Ganesh','Sunil','Anil','Nikhil','Abhishek'],
    female:['Saanvi','Ananya','Pari','Diya','Priya','Aisha','Riya','Aadhya','Ishita','Kiara','Nisha','Pooja','Shruti','Neha','Kavya','Tanvi','Siya','Aditi','Meera','Ritika','Sunita','Geeta','Rekha','Usha','Asha','Lata','Sangita','Archana','Sonal','Bharti','Manisha','Swati','Seema','Deepa','Anita'],
    last:['Sharma','Verma','Gupta','Singh','Kumar','Patel','Joshi','Yadav','Mehta','Shah','Pandey','Nair','Reddy','Iyer','Malhotra','Agarwal','Mishra','Sinha','Bose','Chatterjee','Mukherjee','Banerjee','Das','Roy','Ghosh','Pillai','Menon','Krishnan','Rajan','Varma'],
    streets:['MG Road','Nehru Street','Gandhi Nagar','Rajaji Road','Station Road','Park Street','Brigade Road','Anna Salai','SV Road','Linking Road','FC Road','Bund Garden Road','Residency Road','Church Street','Commercial Street'],
    apt:['Flat 304','A-12','Block B Flat 5','House No. 23','Flat 201','No. 7','Unit 3C','Apt 15','B-204','Flat 7A'],
    cities:[{n:'Mumbai',z:'400001'},{n:'Mumbai',z:'400050'},{n:'Mumbai',z:'400069'},{n:'Delhi',z:'110001'},{n:'Delhi',z:'110034'},{n:'Bangalore',z:'560001'},{n:'Bangalore',z:'560025'},{n:'Hyderabad',z:'500001'},{n:'Chennai',z:'600001'},{n:'Kolkata',z:'700001'},{n:'Pune',z:'411001'},{n:'Jaipur',z:'302001'},{n:'Ahmedabad',z:'380001'},{n:'Surat',z:'395001'},{n:'Lucknow',z:'226001'},{n:'Chandigarh',z:'160001'}],
    phone:function(){return '+91 '+r(70000,99999)+' '+r(10000,99999)}},

  BR:{name:'Brazil',
    male:['Miguel','Arthur','Heitor','Théo','Davi','Gabriel','Pedro','Enzo','Matheus','Lucas','Luan','Gustavo','Rafael','Felipe','Bruno','Leonardo','Victor','Samuel','Daniel','Henrique','Carlos','Antonio','José','Paulo','João','Marcos','André','Leandro','Rodrigo','Renato'],
    female:['Alice','Sofia','Helena','Valentina','Laura','Isabella','Manuela','Júlia','Heloísa','Lara','Lívia','Gabriela','Beatriz','Letícia','Ana','Clara','Mariana','Giovanna','Luisa','Natalia','Patricia','Fernanda','Camila','Amanda','Vanessa','Roberta','Cristina','Sandra','Luciana','Adriana'],
    last:['Silva','Santos','Oliveira','Souza','Rodrigues','Ferreira','Alves','Pereira','Lima','Gomes','Costa','Ribeiro','Martins','Carvalho','Almeida','Lopes','Sousa','Fernandes','Cavalcanti','Monteiro','Cardoso','Nascimento','Araújo','Pinto','Azevedo','Teixeira','Vieira','Ramos','Nunes','Moreira'],
    streets:['Rua das Flores','Av. Paulista','Rua Augusta','Rua Oscar Freire','Av. Atlântica','Rua XV de Novembro','Av. Beira Mar','Rua da Consolação','Av. Brasil','Rua Getúlio Vargas','Av. Rio Branco','Rua Direita','Rua do Comércio','Av. Central','Rua São Paulo'],
    apt:['Apto 52','Sala 4','Apto 201','Casa 3','Bloco B Apto 7','Cobertura','Apto 12','Fundos','Apto 33','Bloco A Apto 5'],
    cities:[{n:'São Paulo',z:'01001-000'},{n:'São Paulo',z:'01310-100'},{n:'São Paulo',z:'04038-001'},{n:'Rio de Janeiro',z:'20040-020'},{n:'Rio de Janeiro',z:'22021-001'},{n:'Brasília',z:'70040-010'},{n:'Salvador',z:'40015-970'},{n:'Fortaleza',z:'60025-061'},{n:'Belo Horizonte',z:'30110-010'},{n:'Curitiba',z:'80010-010'},{n:'Manaus',z:'69005-141'},{n:'Recife',z:'50010-230'},{n:'Porto Alegre',z:'90010-280'},{n:'Goiânia',z:'74001-970'}],
    phone:function(){return '+55 ('+r(11,99)+') 9'+r(1000,9999)+'-'+r(1000,9999)}},

  CA:{name:'Canada',
    male:['Liam','Noah','Oliver','William','Benjamin','Lucas','Ethan','Aiden','James','Logan','Alexander','Elijah','Jackson','Sebastian','Jacob','Mason','Owen','Ryan','Nathan','Dylan','Brandon','Justin','Tyler','Connor','Zachary','Cameron','Hunter','Tristan','Colin','Brett'],
    female:['Emma','Olivia','Ava','Isabella','Sophia','Mia','Charlotte','Amelia','Evelyn','Abigail','Harper','Emily','Elizabeth','Sofia','Avery','Scarlett','Madison','Aria','Grace','Chloe','Hannah','Lily','Zoey','Natalie','Addison','Audrey','Brooklyn','Savannah','Leah','Stella'],
    last:['Smith','Johnson','Williams','Brown','Jones','Miller','Davis','Wilson','Anderson','Taylor','Tremblay','Gagnon','Bouchard','Roy','Cote','Leblanc','Morin','Fortin','Girard','Gauthier','Ouellet','Belanger','Bergeron','Pelletier','Lavoie','Beaulieu','Gagné','Martel','Bélanger','Lemire'],
    streets:['Maple Street','Pine Avenue','Oak Drive','Birch Lane','Elm Way','Cedar Road','Victoria Drive','Queen Street','King Street','Main Street','Yonge Street','Bloor Street','Dundas Street','Bathurst Street','Spadina Avenue'],
    apt:['Unit 4','Apt 202','Suite 10','Unit 3B','Apt 7','No. 5','Unit 8C','Suite 1','Apt 14','Unit 6A'],
    cities:[{n:'Toronto',z:'M5H 2N2'},{n:'Toronto',z:'M4W 1A8'},{n:'Toronto',z:'M6G 1Y9'},{n:'Montreal',z:'H2Y 1C6'},{n:'Montreal',z:'H3B 4G7'},{n:'Vancouver',z:'V6B 1A1'},{n:'Calgary',z:'T2P 1J9'},{n:'Ottawa',z:'K1P 1J1'},{n:'Edmonton',z:'T5J 0N3'},{n:'Winnipeg',z:'R3C 0P8'},{n:'Quebec City',z:'G1R 4S9'},{n:'Hamilton',z:'L8P 1A1'},{n:'Halifax',z:'B3J 1S9'},{n:'Victoria',z:'V8W 1N6'}],
    phone:function(){return '+1 ('+r(200,999)+') '+r(200,999)+'-'+r(1000,9999)}},

  AU:{name:'Australia',
    male:['Oliver','William','Jack','Noah','Thomas','Ethan','James','Lucas','Mason','Liam','Henry','Charlie','George','Archie','Lachlan','Patrick','Samuel','Joshua','Caleb','Tyler','Cameron','Blake','Cooper','Hamish','Flynn','Angus','Declan','Dylan','Finn','Zac'],
    female:['Olivia','Charlotte','Ava','Mia','Amelia','Grace','Isla','Sophie','Zoe','Lily','Chloe','Isabella','Ruby','Ella','Hannah','Sienna','Willow','Aria','Matilda','Harper','Imogen','Piper','Poppy','Violet','Freya','Audrey','Stella','Evie','Zara','Lilly'],
    last:['Smith','Jones','Williams','Brown','Wilson','Taylor','Johnson','White','Martin','Anderson','Thompson','Garcia','Robinson','Walker','Harris','Lee','Clark','Lewis','Young','Hall','Scott','Thomas','Moore','King','Wright','Evans','Adams','Mitchell','Mitchell','Hughes'],
    streets:['Bourke Street','Collins Street','Flinders Lane','Elizabeth Street','George Street','Pitt Street','King Street','York Street','Crown Street','William Street','Swanston Street','Macquarie Street','Castlereagh Street','Pitt Street','Kent Street'],
    apt:['Unit 4','Apt 12','Suite 3','Unit 2B','Flat 5','Unit 8','Level 3 No. 6','Unit 1A','Suite 7','Apt 9'],
    cities:[{n:'Sydney',z:'2000'},{n:'Sydney',z:'2010'},{n:'Sydney',z:'2060'},{n:'Melbourne',z:'3000'},{n:'Melbourne',z:'3004'},{n:'Brisbane',z:'4000'},{n:'Perth',z:'6000'},{n:'Adelaide',z:'5000'},{n:'Gold Coast',z:'4217'},{n:'Newcastle',z:'2300'},{n:'Canberra',z:'2600'},{n:'Hobart',z:'7000'},{n:'Darwin',z:'0800'},{n:'Townsville',z:'4810'}],
    phone:function(){return '+61 4'+r(10,99)+' '+r(100,999)+' '+r(100,999)}},

  NL:{name:'Netherlands',
    male:['Liam','Noah','Lucas','Oliver','Finn','Sem','Daan','Jesse','Lars','Tim','Bram','Sven','Niek','Ruben','Thijs','Bas','Joost','Pieter','Erik','Maarten','Dirk','Henk','Wim','Jan','Kees','Rik','Arjan','Jeroen','Michiel','Wouter'],
    female:['Emma','Mia','Sophie','Olivia','Julia','Anouk','Lisa','Anne','Roos','Femke','Sara','Eva','Nina','Hannah','Lotte','Iris','Lies','Floor','Bo','Sanne','Marjolein','Annelies','Ingrid','Claudia','Monique','Marieke','Tineke','Rianne','Simone','Judith'],
    last:['De Jong','Jansen','De Vries','Van den Berg','Van Dijk','Bakker','Janssen','Visser','Smit','Meijer','De Boer','Mulder','De Graaf','Bos','Hendriks','Van Leeuwen','Dekker','Brouwer','Peters','Dijkstra','Van der Berg','Pieters','Schouten','Hoekstra','Kuipers','Vermeer','Van Beek','Willems','Linders','Peeters'],
    streets:['Keizersgracht','Prinsengracht','Herengracht','Vondelstraat','Haarlemmerstraat','Utrechtsestraat','Kalverstraat','Damrak','Leidseplein','Spui','Damstraat','Leidsestraat','Reguliersbreestraat','Nieuwe Hoogstraat'],
    apt:['Apt 3A','Huis','Boven','Onder','Nr. 4','Apt 12','Etage 2','Nr. 7B','Apt 5','Nr. 19C'],
    cities:[{n:'Amsterdam',z:'1011 AB'},{n:'Amsterdam',z:'1016 EG'},{n:'Amsterdam',z:'1054 XZ'},{n:'Rotterdam',z:'3011 AA'},{n:'Rotterdam',z:'3021 AL'},{n:'The Hague',z:'2511 AA'},{n:'Utrecht',z:'3511 AA'},{n:'Eindhoven',z:'5611 AA'},{n:'Tilburg',z:'5038 AA'},{n:'Groningen',z:'9711 AA'},{n:'Almere',z:'1311 AA'},{n:'Breda',z:'4811 AA'},{n:'Nijmegen',z:'6511 AA'},{n:'Leiden',z:'2311 GH'}],
    phone:function(){return '+31 6 '+r(10000000,99999999)}},

  PT:{name:'Portugal',
    male:['João','Pedro','Miguel','Ricardo','André','Bruno','Carlos','Fernando','Nuno','Paulo','Rui','Sérgio','Tiago','Vasco','Afonso','Gonçalo','Henrique','Luís','Rodrigo','Tomás'],
    female:['Ana','Beatriz','Catarina','Diana','Filipa','Inês','Joana','Lara','Mariana','Patrícia','Rita','Sofia','Teresa','Vera','Xuxa','Carla','Cristina','Helena','Isabel','Marta'],
    last:['Silva','Santos','Ferreira','Pereira','Oliveira','Costa','Rodrigues','Martins','Jesus','Sousa','Fernandes','Gonçalves','Gomes','Lopes','Marques','Alves','Almeida','Ribeiro','Pinto','Carvalho'],
    streets:['Rua Augusta','Av. da Liberdade','Rua do Carmo','Rua Garrett','Largo do Chiado','Rua de Santa Catarina','Rua das Flores','Av. dos Aliados','Rua de Cedofeita','Rua do Almada'],
    apt:['R/C Dto','1º Esq','2º Dto','3º Dto','Apt 5','Andar 2','Frente','Trás'],
    cities:[{n:'Lisbon',z:'1000-001'},{n:'Lisbon',z:'1200-001'},{n:'Porto',z:'4000-001'},{n:'Porto',z:'4200-001'},{n:'Braga',z:'4700-001'},{n:'Coimbra',z:'3000-001'},{n:'Faro',z:'8000-001'},{n:'Setúbal',z:'2900-001'},{n:'Funchal',z:'9000-001'}],
    phone:function(){return '+351 9'+r(10,99)+' '+r(100,999)+' '+r(100,999)}},

  SE:{name:'Sweden',
    male:['Lars','Erik','Karl','Anders','Johan','Per','Nils','Björn','Sven','Mikael','Stefan','Joakim','Patrik','Daniel','Marcus','Alexander','Viktor','Oscar','Emil','William'],
    female:['Maria','Anna','Ingrid','Kristina','Eva','Karin','Helena','Birgitta','Sara','Lena','Emma','Maja','Ida','Julia','Linnea','Klara','Alice','Wilma','Ebba','Elsa'],
    last:['Andersson','Johansson','Karlsson','Nilsson','Eriksson','Larsson','Olsson','Persson','Svensson','Gustafsson','Pettersson','Jonsson','Jansson','Hansson','Bengtsson','Jönsson','Lindström','Jakobsson','Magnusson','Olofsson'],
    streets:['Kungsgatan','Drottninggatan','Storgatan','Vasagatan','Birger Jarlsgatan','Sveavägen','Götgatan','Södermalmsallén','Hamngatan','Hornsgatan'],
    apt:['Lgh 1101','Lgh 2202','Lgh 3A','Lgh 12','Vån 2','Lgh 101','Lgh 5B','Ög 3'],
    cities:[{n:'Stockholm',z:'111 20'},{n:'Stockholm',z:'114 34'},{n:'Gothenburg',z:'411 01'},{n:'Gothenburg',z:'412 63'},{n:'Malmö',z:'211 20'},{n:'Uppsala',z:'751 05'},{n:'Linköping',z:'582 22'},{n:'Örebro',z:'702 10'},{n:'Västerås',z:'721 87'}],
    phone:function(){return '+46 7'+r(0,9)+'-'+r(100,999)+' '+r(10,99)+' '+r(10,99)}},

  NO:{name:'Norway',
    male:['Nils','Lars','Bjørn','Erik','Knut','Johan','Ole','Tor','Svein','Arne','Andreas','Christian','Magnus','Morten','Kristian','Thomas','Simen','Jonas','Henrik','Martin'],
    female:['Anne','Kari','Ingrid','Marit','Kristin','Hanne','Astrid','Gro','Tone','Silje','Camilla','Maria','Marte','Line','Hilde','Lena','Inger','Solveig','Ragnhild','Berit'],
    last:['Hansen','Johansen','Olsen','Larsen','Andersen','Pedersen','Nilsen','Kristiansen','Jensen','Karlsen','Johnsen','Pettersen','Eriksen','Berg','Haugen','Hagen','Jacobsen','Moen','Strand','Dahl'],
    streets:['Karl Johans gate','Storgata','Grensen','Akersgata','Aker Brygge','Bogstadveien','Thorvald Meyers gate','Bygdøy allé','Drammensveien','Universitetsgata'],
    apt:['Leil. 12','H0101','H0202','Leil. 3A','Etg. 2','H0301','Leil. 5','Etg. 4'],
    cities:[{n:'Oslo',z:'0150'},{n:'Oslo',z:'0181'},{n:'Bergen',z:'5003'},{n:'Trondheim',z:'7010'},{n:'Stavanger',z:'4005'},{n:'Drammen',z:'3001'},{n:'Tromsø',z:'9005'}],
    phone:function(){return '+47 '+r(400,999)+' '+r(10,99)+' '+r(100,999)}},

  PL:{name:'Poland',
    male:['Jakub','Mateusz','Michał','Krzysztof','Marcin','Łukasz','Piotr','Paweł','Karol','Kamil','Tomasz','Bartosz','Grzegorz','Marek','Stanisław','Andrzej','Zbigniew','Dariusz','Sławomir','Robert'],
    female:['Anna','Maria','Katarzyna','Małgorzata','Agnieszka','Barbara','Ewa','Elżbieta','Krystyna','Zofia','Monika','Joanna','Teresa','Beata','Magdalena','Natalia','Paulina','Alicja','Weronika','Aleksandra'],
    last:['Nowak','Kowalski','Wiśniewski','Wójcik','Kowalczyk','Kamiński','Lewandowski','Zieliński','Szymański','Woźniak','Dąbrowski','Kozłowski','Jankowski','Mazur','Wojciechowski','Kwiatkowski','Krawczyk','Kaczmarek','Piotrowski','Grabowski'],
    streets:['ul. Marszałkowska','ul. Nowy Świat','ul. Krakowskie Przedmieście','ul. Floriańska','ul. Grodzka','Al. Jerozolimskie','ul. Piotrkowska','ul. Świdnicka','ul. Długa','ul. Mostowa'],
    apt:['Mieszk. 12','M. 3A','Lok. 7','Piętro 2','M. 5B','Lok. 14','Mieszk. 1','M. 8C'],
    cities:[{n:'Warsaw',z:'00-001'},{n:'Warsaw',z:'00-950'},{n:'Kraków',z:'30-001'},{n:'Łódź',z:'90-001'},{n:'Wrocław',z:'50-001'},{n:'Poznań',z:'60-001'},{n:'Gdańsk',z:'80-001'},{n:'Szczecin',z:'70-001'},{n:'Bydgoszcz',z:'85-001'}],
    phone:function(){return '+48 '+r(500,799)+' '+r(100,999)+' '+r(100,999)}},

  CH:{name:'Switzerland',
    male:['Hans','Peter','Thomas','Daniel','Martin','Stefan','Markus','Andreas','Christian','Patrick','Michael','David','Simon','Lukas','Tobias','Fabian','Raphael','Florian','Dominik','Nico'],
    female:['Anna','Maria','Sarah','Laura','Sandra','Andrea','Nicole','Christine','Barbara','Silvia','Claudia','Elisabeth','Katharina','Stephanie','Nadine','Petra','Martina','Julia','Miriam','Sabrina'],
    last:['Müller','Meier','Schmid','Keller','Weber','Huber','Schneider','Meyer','Steiner','Fischer','Bachmann','Brunner','Zimmermann','Baumann','Maurer','Küng','Bauer','Moser','Frei','Schwarz'],
    streets:['Bahnhofstrasse','Rämistrasse','Limmatquai','Marktgasse','Langstrasse','Uraniastrasse','Talstrasse','Münstergasse','Rosengasse','Theaterstrasse'],
    apt:['Whg. 3','App. 12','Whg. 5A','EG','1. OG','App. 7','Whg. 2B','3. OG'],
    cities:[{n:'Zurich',z:'8001'},{n:'Zurich',z:'8004'},{n:'Geneva',z:'1201'},{n:'Geneva',z:'1204'},{n:'Basel',z:'4001'},{n:'Bern',z:'3001'},{n:'Lausanne',z:'1001'},{n:'Winterthur',z:'8400'},{n:'Lucerne',z:'6003'}],
    phone:function(){return '+41 7'+r(6,9)+' '+r(100,999)+' '+r(10,99)+' '+r(10,99)}},

  MX:{name:'Mexico',
    male:['José','Luis','Juan','Carlos','Miguel','Roberto','Alejandro','Francisco','Manuel','Eduardo','Ricardo','Daniel','Sergio','Fernando','Héctor','Mario','Óscar','Javier','Pablo','Andrés'],
    female:['María','Guadalupe','Mariana','Sofía','Valentina','Fernanda','Daniela','Alejandra','Claudia','Gabriela','Adriana','Laura','Karla','Paola','Verónica','Sandra','Patricia','Rosa','Isabel','Carmen'],
    last:['García','Martínez','López','González','Hernández','Pérez','Rodríguez','Sánchez','Ramírez','Cruz','Flores','Torres','Rivera','Gómez','Díaz','Morales','Vásquez','Álvarez','Reyes','Castillo'],
    streets:['Av. Insurgentes','Paseo de la Reforma','Av. Juárez','Calle Madero','Av. Universidad','Av. Hidalgo','Calle Morelos','Av. Revolución','Calle Guerrero','Av. Independencia'],
    apt:['Depto 3B','Int. 12','Apt. 5','Piso 2','Depto 8A','Planta Baja','Int. 7','Depto 1C'],
    cities:[{n:'Mexico City',z:'06600'},{n:'Mexico City',z:'11000'},{n:'Guadalajara',z:'44100'},{n:'Monterrey',z:'64000'},{n:'Puebla',z:'72000'},{n:'Cancún',z:'77500'},{n:'Tijuana',z:'22000'},{n:'León',z:'37000'}],
    phone:function(){return '+52 55 '+r(1000,9999)+' '+r(1000,9999)}},

  KR:{name:'South Korea',
    male:['Minjun','Siwoo','Dohyun','Junwoo','Jihoon','Seojun','Jaehyun','Jungwoo','Hyunwoo','Yujun','Seungmin','Minseok','Donghyun','Sanghyun','Hyunsik'],
    female:['Seoyeon','Hayoon','Jiwon','Sohyun','Jiyeon','Minji','Yuna','Chaeyoung','Eunji','Dahyun','Jisoo','Hyeri','Nayeon','Jennie','Irene'],
    last:['Kim','Lee','Park','Choi','Jeong','Kang','Cho','Yun','Jang','Lim','Han','Oh','Seo','Shin','Kwon','Hwang','Ahn','Song','Hong','Yu'],
    streets:['Gangnam-daero','Teheran-ro','Sejong-daero','Jongno','Eulji-ro','Cheonggyecheon-ro','Insadong-gil','Hongdae-ro','Bukhansan-ro','Incheon-ro'],
    apt:['101호','202호','303호','B동 401호','A동 502호','1201호','701호','연립 3호'],
    cities:[{n:'Seoul',z:'04524'},{n:'Seoul',z:'06236'},{n:'Busan',z:'48058'},{n:'Incheon',z:'22320'},{n:'Daegu',z:'41945'},{n:'Daejeon',z:'35220'},{n:'Gwangju',z:'61469'},{n:'Suwon',z:'16499'}],
    phone:function(){return '+82 10-'+r(1000,9999)+'-'+r(1000,9999)}},

  CN:{name:'China',
    male:['Wei','Fang','Yong','Jun','Jian','Lei','Hao','Ming','Bin','Chao','Yang','Dong','Peng','Tao','Yu','Long','Jie','Feng','Zhen','Kai'],
    female:['Fang','Li','Min','Na','Xia','Hong','Ying','Juan','Mei','Xin','Qing','Yan','Hui','Lin','Jing','Hua','Yun','Xue','Dan','Ling'],
    last:['Wang','Li','Zhang','Liu','Chen','Yang','Huang','Zhao','Wu','Zhou','Xu','Sun','Ma','Zhu','Hu','Guo','He','Gao','Lin','Luo'],
    streets:['长安街','南京路','中山路','人民路','解放路','建国路','和平路','光明路','幸福路','新华路'],
    apt:['3单元201室','2单元502室','A座1803室','1单元301室','B栋405室','东区12楼','西区6号','北苑3-502'],
    cities:[{n:'Beijing',z:'100001'},{n:'Shanghai',z:'200001'},{n:'Guangzhou',z:'510001'},{n:'Shenzhen',z:'518001'},{n:'Chengdu',z:'610001'},{n:'Hangzhou',z:'310001'},{n:'Wuhan',z:'430001'},{n:'Nanjing',z:'210001'},{n:'Xi\'an',z:'710001'}],
    phone:function(){return '+86 1'+r(30,99)+' '+r(1000,9999)+' '+r(1000,9999)}},

  ZA:{name:'South Africa',
    male:['Sipho','Bongani','Thabo','Siyanda','Lethiwe','Sandile','Mthokozisi','Lungelo','Sifiso','Nhlanhla','Tebogo','Lesego','Kgosi','Lebogang','Motheo'],
    female:['Nomsa','Zanele','Thandi','Siphokazi','Nokuthula','Lindiwe','Busisiwe','Nompumelelo','Gugu','Tebogo','Katlego','Dimakatso','Ntombi','Bongiwe','Lungile'],
    last:['Dlamini','Nkosi','Sithole','Mthembu','Nxumalo','Khumalo','Shabalala','Mkhize','Ntuli','Ngcobo','Mokoena','Molefe','Kgosana','Mabunda','Mahlangu'],
    streets:['Long Street','Victoria Road','Commissioner Street','Main Road','Church Street','Adderley Street','Jan Smuts Avenue','Oxford Road','William Nicol Drive','Rivonia Road'],
    apt:['Unit 4','Flat 2A','Apt 12','Suite 3','Unit 8B','Flat 5','No. 7','Block C Flat 3'],
    cities:[{n:'Johannesburg',z:'2001'},{n:'Cape Town',z:'8001'},{n:'Durban',z:'4001'},{n:'Pretoria',z:'0001'},{n:'Port Elizabeth',z:'6001'},{n:'Bloemfontein',z:'9300'},{n:'East London',z:'5200'}],
    phone:function(){return '+27 '+r(60,81)+' '+r(100,999)+' '+r(1000,9999)}},

  TR:{name:'Turkey',
    male:['Mehmet','Mustafa','Ahmed','Ali','Hüseyin','Hasan','İbrahim','Halil','İsmail','Osman','Murat','Emre','Ahmet','Burak','Can','Cem','Furkan','Umut','Serhat','Kerem'],
    female:['Fatma','Ayşe','Emine','Hatice','Zeynep','Elif','Esra','Büşra','Merve','Selin','Tuğba','Gamze','Özge','Ceren','Pınar','Derya','Gül','Sevgi','Nurcan','Arzu'],
    last:['Yılmaz','Kaya','Demir','Şahin','Çelik','Yıldız','Yıldırım','Öztürk','Aydın','Özdemir','Arslan','Doğan','Kılıç','Aslan','Çetin','Koç','Kurt','Ak','Şimşek','Polat'],
    streets:['İstiklal Caddesi','Bağdat Caddesi','Atatürk Caddesi','Cumhuriyet Caddesi','Kızılay Caddesi','Anafartalar Caddesi','Tunalı Hilmi Caddesi','Barbaros Bulvarı'],
    apt:['Kat:3 No:12','Daire 5','Kat:2 Daire 8','Apt. 4A','Daire 15','Kat:1','Zemin Kat','Daire 7B'],
    cities:[{n:'Istanbul',z:'34000'},{n:'Istanbul',z:'34100'},{n:'Ankara',z:'06010'},{n:'Izmir',z:'35210'},{n:'Bursa',z:'16010'},{n:'Antalya',z:'07010'},{n:'Adana',z:'01010'},{n:'Konya',z:'42010'}],
    phone:function(){return '+90 5'+r(30,99)+' '+r(100,999)+' '+r(10,99)+' '+r(10,99)}},

  NG:{name:'Nigeria',
    male:['Emeka','Chukwu','Tunde','Seun','Biodun','Kayode','Adewale','Femi','Olumide','Babatunde','Chidi','Nnamdi','Ifeanyi','Obinna','Chisom'],
    female:['Ngozi','Amaka','Chidinma','Adaeze','Ifeoma','Aisha','Fatima','Hauwa','Kemi','Funke','Bisi','Toyin','Yetunde','Shade','Nneka'],
    last:['Adeyemi','Okafor','Nwosu','Eze','Okonkwo','Adesanya','Olawale','Ibrahim','Musa','Bello','Lawal','Abdullahi','Osei','Mensah','Asante'],
    streets:['Victoria Island','Broad Street','Lagos Island','Ahmadu Bello Way','Awolowo Road','Ozumba Mbadiwe','Adeola Odeku Street','Saka Tinubu Street'],
    apt:['Flat 4','No. 12','Suite 2B','Block A Flat 3','No. 7','Apt 15','Unit 6','Flat 9C'],
    cities:[{n:'Lagos',z:'100001'},{n:'Lagos',z:'101001'},{n:'Abuja',z:'900001'},{n:'Kano',z:'700001'},{n:'Ibadan',z:'200001'},{n:'Port Harcourt',z:'500001'},{n:'Enugu',z:'400001'}],
    phone:function(){return '+234 '+r(700,909)+' '+r(100,999)+' '+r(1000,9999)}},

  PH:{name:'Philippines',
    male:['Jose','Juan','Antonio','Manuel','Eduardo','Ricardo','Roberto','Francisco','Miguel','Carlos','Angelo','Christian','Joshua','Mark','John','Jerome','Ryan','Kevin','Michael','Joseph'],
    female:['Maria','Ana','Rosa','Elena','Carmen','Teresa','Luz','Grace','Faith','Hope','Charity','Jocelyn','Michelle','Kristine','Maricel','Joyce','Joanna','Jennifer','Patricia','Angelica'],
    last:['Santos','Reyes','Cruz','Bautista','Ocampo','Garcia','Torres','Flores','Dela Cruz','Lopez','Ramos','Aquino','Hernandez','Villanueva','Mendoza','Castillo','Rivera','Gonzales','Morales','Manalang'],
    streets:['Roxas Boulevard','EDSA','Ayala Avenue','Katipunan Avenue','Ortigas Avenue','Commonwealth Avenue','Taft Avenue','España Boulevard','Session Road','Magsaysay Avenue'],
    apt:['Unit 4B','Rm. 302','Unit 12A','Blk 3 Lot 5','Unit 7','No. 15','Suite 2A','Unit 9C'],
    cities:[{n:'Manila',z:'1000'},{n:'Quezon City',z:'1100'},{n:'Cebu City',z:'6000'},{n:'Davao City',z:'8000'},{n:'Makati',z:'1200'},{n:'Pasig',z:'1600'},{n:'Taguig',z:'1630'},{n:'Caloocan',z:'1400'}],
    phone:function(){return '+63 9'+r(10,99)+' '+r(100,999)+' '+r(1000,9999)}},

  ID:{name:'Indonesia',
    male:['Budi','Adi','Agus','Bambang','Dedi','Eko','Fajar','Guntur','Hendra','Irwan','Joko','Komang','Lukman','Made','Nanda','Oki','Putu','Rachmat','Slamet','Wahyu'],
    female:['Sari','Dewi','Rina','Wulan','Ayu','Dian','Fitri','Hani','Indah','Karina','Lestari','Maya','Nita','Putri','Ratna','Sri','Tini','Ulfa','Vina','Wati'],
    last:['Susanto','Wijaya','Santoso','Kusuma','Atmaja','Setiawan','Hidayat','Nugroho','Prasetyo','Wibowo','Hartono','Suryadi','Gunawan','Halim','Kurniawan','Putra','Permana','Rahayu','Dewanti','Suharto'],
    streets:['Jl. Sudirman','Jl. Thamrin','Jl. Gatot Subroto','Jl. Kuningan','Jl. Imam Bonjol','Jl. Diponegoro','Jl. Cikini','Jl. Malioboro','Jl. Ahmad Yani','Jl. Pahlawan'],
    apt:['Unit 12A','Lt. 3 No. 5','Apt. 7B','No. 23','Unit 4C','Lt. 2','Blok A No. 8','Unit 15'],
    cities:[{n:'Jakarta',z:'10110'},{n:'Jakarta',z:'10210'},{n:'Surabaya',z:'60111'},{n:'Bandung',z:'40111'},{n:'Medan',z:'20111'},{n:'Semarang',z:'50111'},{n:'Yogyakarta',z:'55111'},{n:'Makassar',z:'90111'},{n:'Bali',z:'80111'}],
    phone:function(){return '+62 81'+r(1,9)+'-'+r(1000,9999)+'-'+r(1000,9999)}},

  MY:{name:'Malaysia',
    male:['Ahmad','Mohammed','Ali','Hassan','Ibrahim','Ismail','Abdullah','Azman','Razif','Fariz','Wei Ming','Chong','Lim','Tan','Wong','Raj','Kumar','Suresh','Ravi','Arjun'],
    female:['Siti','Nur','Aishah','Farah','Nurul','Zainab','Rohani','Aminah','Azizah','Fatimah','Mei Ling','Hui Yen','Li Ying','Nora','Poh Lin','Priya','Vimala','Geetha','Kavitha','Lakshmi'],
    last:['Ahmad','Mohamed','Abdullah','Ibrahim','Ismail','Hassan','Rahman','Razali','Othman','Yusof','Tan','Lim','Wong','Lee','Ng','Ong','Rajasekaran','Krishnan','Murugan','Chandran'],
    streets:['Jalan Bukit Bintang','Jalan Ampang','Jalan Tuanku Abdul Halim','Jalan Raja Chulan','Jalan Imbi','Jalan Masjid India','Jalan Chow Kit','Jalan Ipoh','Jalan Pahang','Jalan Semarak'],
    apt:['Unit 12-3','Apt 4A','Suite 22B','No. 8','Unit 6C','Tingkat 3','Blok A-5','Unit 15B'],
    cities:[{n:'Kuala Lumpur',z:'50000'},{n:'Kuala Lumpur',z:'50480'},{n:'George Town',z:'10050'},{n:'Johor Bahru',z:'80000'},{n:'Kota Kinabalu',z:'88000'},{n:'Ipoh',z:'30000'},{n:'Shah Alam',z:'40150'}],
    phone:function(){return '+60 1'+r(1,9)+'-'+r(1000,9999)+' '+r(1000,9999)}},

  AR:{name:'Argentina',
    male:['Mateo','Santiago','Sebastián','Tomás','Benjamín','Nicolás','Facundo','Agustín','Ignacio','Federico','Gonzalo','Ezequiel','Rodrigo','Martín','Pablo','Lucas','Diego','Leandro','Javier','Hernán'],
    female:['Valentina','Camila','Sofía','Isabella','Martina','Agustina','Florencia','Rocío','Luciana','Noelia','Belén','Natalia','Daniela','Paola','Romina','Mariana','Verónica','Giselle','Laura','Carolina'],
    last:['González','Rodríguez','Gómez','Fernández','López','Díaz','Martínez','Pérez','García','Sánchez','Romero','Torres','Ramírez','Flores','Acosta','Mendez','Ruiz','Castro','Medina','Ortiz'],
    streets:['Av. Corrientes','Florida','Av. Santa Fe','Av. de Mayo','Avenida 9 de Julio','Av. Callao','Av. Rivadavia','Lavalle','Av. Cabildo','Av. Belgrano'],
    apt:['Depto 3B','Piso 2 Dpto A','Piso 4','Int. 12','Depto 8','Planta Baja','Int. 5A','Piso 7 Dpto C'],
    cities:[{n:'Buenos Aires',z:'C1001'},{n:'Buenos Aires',z:'C1010'},{n:'Córdoba',z:'X5000'},{n:'Rosario',z:'S2000'},{n:'Mendoza',z:'M5500'},{n:'La Plata',z:'B1900'},{n:'Mar del Plata',z:'B7600'},{n:'Salta',z:'A4400'}],
    phone:function(){return '+54 9 11 '+r(1000,9999)+'-'+r(1000,9999)}},

  EG:{name:'Egypt',
    male:['Mohamed','Ahmed','Mahmoud','Omar','Ali','Hassan','Hussein','Ibrahim','Khaled','Tarek','Youssef','Amr','Amir','Sherif','Hossam','Karim','Walid','Nasser','Samir','Alaa'],
    female:['Fatima','Mariam','Nour','Hana','Amal','Sara','Dina','Rania','Mona','Eman','Sahar','Noha','Doaa','Heba','Mai','Ola','Radwa','Shimaa','Yasmin','Nadine'],
    last:['Mohamed','Ahmed','Hassan','Ibrahim','Ali','Mahmoud','Hussein','Mostafa','Omar','Kamal','Gamal','Saad','Abdel','Nasser','Salem','Attia','Zaki','Fathy','Mansour','Ragab'],
    streets:['شارع التحرير','شارع النيل','شارع رمسيس','شارع الجمهورية','شارع صلاح سالم','شارع عصمت','طريق الإسكندرية الصحراوي','شارع السلام'],
    apt:['شقة 5','دور 3 شقة 2','الدور الأرضي','شقة 12 ب','عمارة 4','دور 7','وحدة 3 أ','شقة 8'],
    cities:[{n:'Cairo',z:'11511'},{n:'Cairo',z:'11371'},{n:'Alexandria',z:'21111'},{n:'Giza',z:'12111'},{n:'Shubra El Kheima',z:'13711'},{n:'Port Said',z:'42111'},{n:'Suez',z:'43511'}],
    phone:function(){return '+20 1'+r(0,2)+r(0,9)+' '+r(1000,9999)+' '+r(1000,9999)}},

  TH:{name:'Thailand',
    male:['Somchai','Somsak','Surachai','Wichai','Prasit','Nattapong','Kritsana','Pongsakorn','Chaiyong','Supachai','Thanakorn','Weerawit','Apichat','Sompong','Boonchai'],
    female:['Siriporn','Malee','Nisa','Pajaree','Patchara','Rungnapa','Siriwan','Thanyarat','Wipawan','Yupin','Anchana','Duangkamol','Jiraporn','Kannikar','Ladda'],
    last:['Srisombat','Wongkham','Tancharoen','Phetsri','Rattanasuwan','Boonsong','Chotirut','Daengdao','Eamsa-ard','Fakthong','Khamthong','Lertprasert','Nantawong','Phongphaew','Rungrat'],
    streets:['Sukhumvit Road','Silom Road','Rama IV Road','Charoenkrung Road','Ratchadamri Road','Phetchaburi Road','Lat Phrao Road','Bangna Road','Asoke Road','Sathorn Road'],
    apt:['ห้อง 302','ยูนิต 12A','ห้อง 5B','ชั้น 3','ยูนิต 8','ห้อง 201','ยูนิต 4C','ชั้น 7 ห้อง 3'],
    cities:[{n:'Bangkok',z:'10100'},{n:'Bangkok',z:'10110'},{n:'Chiang Mai',z:'50000'},{n:'Pattaya',z:'20150'},{n:'Phuket',z:'83000'},{n:'Khon Kaen',z:'40000'},{n:'Nakhon Ratchasima',z:'30000'}],
    phone:function(){return '+66 '+r(61,99)+' '+r(100,999)+' '+r(1000,9999)}},

  GH:{name:'Ghana',
    male:['Kwame','Kofi','Kwesi','Yaw','Kwaku','Kojo','Kwabena','Akwasi','Fiifi','Kobby','Ato','Ekow','Nana','Ebo','Sena'],
    female:['Abena','Akua','Adwoa','Yaa','Ama','Afua','Afia','Akosua','Awura','Araba','Esi','Efua','Adoma','Abenaa','Serwaa'],
    last:['Mensah','Asante','Boateng','Osei','Amoah','Kwarteng','Acheampong','Darko','Agyemang','Appiah','Owusu','Ofori','Adjei','Tetteh','Quaye'],
    streets:['Accra-Tema Motorway','Liberation Road','High Street','Cantonments Road','Airport Road','Spintex Road','Ring Road Central','Castle Road'],
    apt:['House No. 3','Apt 12','Unit 4B','No. 7','Block C Flat 2','House 15A','Unit 8','No. 23'],
    cities:[{n:'Accra',z:'GA-039'},{n:'Kumasi',z:'KS-000'},{n:'Tamale',z:'NR-001'},{n:'Takoradi',z:'WR-001'},{n:'Cape Coast',z:'CR-001'}],
    phone:function(){return '+233 '+r(20,59)+' '+r(100,999)+' '+r(1000,9999)}}
};
