export const HERO_TEXTS = [
  'All Tools You Need',
  'Fast. Simple. Powerful.',
  'Everything In Your Browser.',
]

export const CAT_COLORS = {
  Security: { bg:'#FFF0F5', text:'#B71C1C', border:'rgba(183,28,28,.15)' },
  Text:     { bg:'#F3F0FF', text:'#5B21B6', border:'rgba(91,33,182,.15)' },
  Math:     { bg:'#E8F5E9', text:'#1B5E20', border:'rgba(27,94,32,.15)' },
  Finance:  { bg:'#FFF8E1', text:'#E65100', border:'rgba(230,81,0,.15)' },
  Design:   { bg:'#E8F4FD', text:'#0D47A1', border:'rgba(13,71,161,.15)' },
  Inspire:  { bg:'#FCE4EC', text:'#880E4F', border:'rgba(136,14,79,.15)' },
  Social:   { bg:'#E8EAF6', text:'#1A237E', border:'rgba(26,35,126,.15)' },
  Image:    { bg:'#E0F7FA', text:'#004D40', border:'rgba(0,77,64,.15)' },
  Document: { bg:'#FFF3E0', text:'#BF360C', border:'rgba(191,54,12,.15)' },
  Utility:  { bg:'#F1F8E9', text:'#33691E', border:'rgba(51,105,30,.15)' },
  Vault:    { bg:'#FBE9E7', text:'#BF360C', border:'rgba(191,54,12,.15)' },
  Generate: { bg:'#E8EAF6', text:'#283593', border:'rgba(40,53,147,.15)' },
  Dev:      { bg:'#E8F0FE', text:'#1565C0', border:'rgba(21,101,192,.15)' },
  Video:    { bg:'#FFF3E0', text:'#E65100', border:'rgba(230,81,0,.15)' },
  SEO:      { bg:'#E8F5E9', text:'#1B5E20', border:'rgba(27,94,32,.15)' },
  AI:       { bg:'#F3E8FF', text:'#6B21A8', border:'rgba(107,33,168,.15)' },
}

export const TOOLS = [
  { id:'password',    em:'🛡️', icon:'/icons/icon-password.jpeg',    title:'Password Generator',       cat:'Security', desc:'Create ultra-secure passwords with custom rules and entropy analysis.',                   path:'/tools/password'    },
  { id:'wordcount',   em:'📊', icon:'/icons/icon-wordcount.jpeg',   title:'Word Counter',              cat:'Text',     desc:'Real-time word, character, sentence and reading time analysis.',                        path:'/tools/wordcount'   },
  { id:'textcase',    em:'✏️', icon:'/icons/icon-textcase.jpeg',    title:'Text Case Converter',       cat:'Text',     desc:'Transform text to UPPER, lower, camelCase, snake_case and 7 more.',                    path:'/tools/textcase'    },
  { id:'units',       em:'📏', icon:'/icons/icon-units.jpeg',       title:'Unit Converter',            cat:'Math',     desc:'Convert length, weight, area, volume, speed and temperature.',                          path:'/tools/units'       },
  { id:'currency',    em:'💸', icon:'/icons/icon-currency.jpeg',    title:'Currency Converter',        cat:'Finance',  desc:'Convert between 25+ world currencies with live reference rates.',                      path:'/tools/currency'    },
  { id:'gradient',    em:'🌈', icon:'/icons/icon-gradient.jpeg',    title:'Gradient Generator',        cat:'Design',   desc:'Build beautiful CSS gradients visually and copy the code instantly.',                  path:'/tools/gradient'    },
  { id:'quote',       em:'💬', icon:'/icons/icon-quote.jpeg',       title:'Quote Generator',           cat:'Inspire',  desc:'Discover inspiring quotes with favorites and browseable library.',                     path:'/tools/quote'       },
  { id:'favicon',     em:'🌐', icon:'/icons/icon-favicon.jpeg',     title:'Favicon Generator',         cat:'Design',   desc:'Turn any text, emoji or image into a downloadable favicon.',                          path:'/tools/favicon'     },
  { id:'thumbnail',   em:'🎬', icon:'/icons/icon-thumbnail.jpeg',   title:'Social Media Thumbnail',         cat:'Social',   desc:"Preview any YouTube video's thumbnails in all resolutions.",                          path:'/tools/thumbnail'   },
  { id:'imgresizer',  em:'🔭', icon:'/icons/icon-imgresizer.jpeg',  title:'Image Resizer',             cat:'Image',    desc:'Resize images to exact dimensions with aspect ratio lock and live preview.',          path:'/tools/imgresizer'  },
  { id:'imgcompress', em:'🗜️', icon:'/icons/icon-imgcompress.jpeg', title:'Image Compressor',          cat:'Image',    desc:'Compress images up to 90% smaller with real-time size comparison.',                  path:'/tools/imgcompress' },
  { id:'imgconvert',  em:'♻️', icon:'/icons/icon-imgconvert.jpeg',  title:'Image Converter',           cat:'Image',    desc:'Convert between PNG, JPEG, and WebP formats instantly in browser.',                   path:'/tools/imgconvert'  },
  { id:'bgremove',    em:'🪄', icon:'/icons/icon-bgremove.jpeg',    title:'BG Remover',                cat:'Image',    desc:'Remove solid backgrounds from images entirely in your browser.',                      path:'/tools/bgremove'    },
  { id:'pdf',         em:'📄', icon:'/icons/icon-pdf.jpeg',         title:'PDF Studio & Toolkit',       cat:'Document', desc:'Convert DOCX, images & data to PDF, export PNG/JPG, merge, split, reorder, compress & watermark.', path:'/tools/pdf'         },
  { id:'aspectratio', em:'📐', icon:'/icons/icon-aspectratio.jpeg', title:'Aspect Ratio Calculator',   cat:'Math',     desc:'Live canvas morphing rectangle. Calculate and match any aspect ratio.',               path:'/tools/aspectratio' },
  { id:'fileconvert', em:'⚡', icon:'/icons/icon-fileconvert.jpeg', title:'File Converter', cat:'Utility', desc:'Convert documents, images, audio, video, CSV, JSON, PDF and more — all in your browser.', path:'/tools/fileconvert' },
  { id:'vault',       em:'🔒', icon:'/icons/icon-vault.jpeg',       title:'Password Vault',            cat:'Vault',    desc:'Secure local password manager with vault door animation and card flips.',             path:'/tools/vault'       },
  { id:'imagetools',   em:'✨', icon:'/icons/icon-imgborder.jpeg',   title:'Image Tools Studio',        cat:'Image',    desc:'Professional manual crop, image redactor, OCR text extraction, DPI analysis, borders & effects in one studio.', path:'/tools/image-tools' },
  { id:'randname',    em:'👤', icon:'/icons/icon-randname.jpeg',    title:'Random Name Generator',     cat:'Generate', desc:'Generate realistic names from 30+ countries with phone, email and more.',          path:'/tools/randname'    },
  { id:'randaddress', em:'🗺️', icon:'/icons/icon-randaddress.jpeg', title:'Random Address Generator',  cat:'Generate', desc:'Generate real-format addresses from 30+ countries with ZIP codes and phone.',       path:'/tools/randaddress' },
  { id:'wordreplace', em:'🔍', icon:'/icons/icon-wordreplace.jpeg', title:'Word Replacer',             cat:'Text',     desc:'Find and replace any word or phrase in your text with live preview and history.',   path:'/tools/wordreplace' },
  { id:'bcrypt',      em:'🔐', icon:'/icons/icon-bcrypt.jpeg',      title:'Bcrypt Hash Generator',     cat:'Security', desc:'Generate, hash and verify bcrypt passwords with configurable cost rounds.',           path:'/tools/bcrypt'      },
  { id:'colorpicker', em:'🎨', icon:'/icons/icon-colorpicker.jpeg',  title:'Color Picker',              cat:'Design',  desc:'Pick, convert and analyze colors with WCAG contrast checker and shade generator.',   path:'/tools/colorpicker' },
  { id:'videoscreenshot',  em:'🎬', icon:'/icons/icon-videoscreenshot.jpeg',   title:'Video Screenshot Extractor', cat:'Video',   desc:'Extract frames from any video at custom intervals. Export as PNG, JPG or WEBP zip.',   path:'/tools/video-screenshot'    },
  { id:'videotranscriber',  em:'🎙️', icon:'/icons/icon-videotranscriber.jpeg',  title:'Video Transcriber',          cat:'Video',   desc:'Transcribe any video to text with AI-powered Groq Whisper. Export as TXT, SRT or VTT.',  path:'/tools/video-transcriber'    },
  { id:'websiteanalyzer',  em:'🔍', icon:'/icons/icon-websiteanalyzer.jpeg',   title:'Website Analyzer',           cat:'SEO',     desc:'Full SEO audit, tech stack detection, security scan, performance metrics and competitor comparison.', path:'/tools/website-analyzer' },
  { id:'translator',  em:'🌐', icon:'/icons/icon-translator.jpeg',  title:'Text Translator',  cat:'Text',     desc:'Translate text into 33 languages using DeepL — the most accurate translation engine.',  path:'/tools/translator'  },
  { id:'qrcode',       em:'🔲', icon:'/icons/icon-qrcode.jpeg',      title:'QR & Barcode Studio',       cat:'Generate', desc:'Create custom QR codes, scan QR via camera/upload, and generate or scan multi-format barcodes.', path:'/tools/qrcode'      },
  { id:'breachcheck',  em:'🔓', icon:'/icons/icon-breachcheck.jpeg', title:'Email Breach Checker', cat:'Security', desc:'Check if your email has appeared in known data breaches using Have I Been Pwned.', path:'/tools/breach-check' },
  { id:'iplookup',     em:'🌐', icon:'/icons/icon-iplookup.jpeg',    title:'IP Lookup',         cat:'Utility', desc:'Find location, ISP, timezone and more for any IP address — including your own.', path:'/tools/ip-lookup'   },
  { id:'systeminfo',   em:'💻', icon:'/icons/icon-systeminfo.jpeg',   title:'System Info & Audit', cat:'Dev',     desc:'Full browser, hardware, and client-side privacy & security scan.', path:'/tools/system-info'   },
  { id:'countryfinder', em:'🌍', icon:'/icons/icon-countryfinder.jpeg', title:'Country Data & Fact Finder', cat:'Utility', desc:'Explore details, population, flags, currencies, timezones, and maps for 250+ countries.', path:'/tools/country-finder' },
]

export const QUOTES = [
  { text:'The only way to do great work is to love what you do.',                          author:'Steve Jobs'         },
  { text:'Innovation distinguishes between a leader and a follower.',                       author:'Steve Jobs'         },
  { text:'In the middle of every difficulty lies opportunity.',                             author:'Albert Einstein'    },
  { text:'Imagination is more important than knowledge.',                                   author:'Albert Einstein'    },
  { text:'The best way to predict the future is to invent it.',                            author:'Alan Kay'           },
  { text:'Code is like humor. When you have to explain it, it\'s bad.',                   author:'Cory House'         },
  { text:'First, solve the problem. Then, write the code.',                                 author:'John Johnson'       },
  { text:'Simplicity is the soul of efficiency.',                                           author:'Austin Freeman'     },
  { text:'Make it work, make it right, make it fast.',                                      author:'Kent Beck'          },
  { text:'Clean code always looks like it was written by someone who cares.',              author:'Robert C. Martin'   },
  { text:'Talk is cheap. Show me the code.',                                                author:'Linus Torvalds'     },
  { text:'Stay hungry, stay foolish.',                                                       author:'Steve Jobs'         },
  { text:'Perfection is achieved not when nothing is left to add, but when nothing is left to take away.', author:'Antoine de Saint-Exupéry' },
  { text:'The art of programming is the art of organizing complexity.',                    author:'Edsger Dijkstra'    },
  { text:'Programming isn\'t about what you know; it\'s about what you can figure out.', author:'Chris Pine'         },
  { text:'It\'s not a bug — it\'s an undocumented feature.',                              author:'Anonymous'          },
  { text:'Any fool can write code that a computer can understand.',                         author:'Martin Fowler'      },
  { text:'Don\'t comment bad code — rewrite it.',                                          author:'Brian Kernighan'    },
  { text:'The most powerful tool we have as developers is automation.',                    author:'Scott Hanselman'    },
  { text:'Be curious. Read widely. Try new things.',                                        author:'Aaron Swartz'       },
]

export const UNIT_CATEGORIES = {
  Length:      { units:['km','m','cm','mm','mi','yd','ft','in'],      factors:[1000,1,0.01,0.001,1609.34,0.9144,0.3048,0.0254] },
  Weight:      { units:['kg','g','mg','lb','oz','ton'],               factors:[1,0.001,0.000001,0.453592,0.0283495,1000] },
  Area:        { units:['m²','km²','cm²','ft²','in²','acre'],         factors:[1,1e6,0.0001,0.092903,0.00064516,4046.86] },
  Volume:      { units:['L','mL','m³','gal','fl oz','cup'],           factors:[1,0.001,1000,3.78541,0.0295735,0.24] },
  Speed:       { units:['m/s','km/h','mph','knot'],                   factors:[1,0.27778,0.44704,0.514444] },
  Temperature: { units:['°C','°F','K'], special:true },
  Time:        { units:['ms','s','min','h','day','week','year'],      factors:[0.001,1,60,3600,86400,604800,31536000] },
  Data:        { units:['B','KB','MB','GB','TB','PB'],                factors:[1,1024,1048576,1073741824,1099511627776,1125899906842624] },
  Energy:      { units:['J','kJ','cal','kcal','Wh','kWh'],            factors:[1,1000,4.184,4184,3600,3600000] },
  Pressure:    { units:['Pa','hPa','kPa','bar','psi','atm'],          factors:[1,100,1000,100000,6894.76,101325] },
}

export const CURRENCY_RATES = {
  USD:1, EUR:0.920, GBP:0.790, INR:83.12, JPY:149.5, CAD:1.360, AUD:1.530, CHF:0.890,
  CNY:7.240, SGD:1.340, AED:3.670, SAR:3.750, BRL:4.970, MXN:17.15, KRW:1325, HKD:7.830,
  NOK:10.55, SEK:10.42, DKK:6.890, NZD:1.630, ZAR:18.63, TRY:30.50, THB:35.10, RUB:91.30, PKR:278, IDR:15750, MYR:4.72, PHP:56.42,
}
